//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package semana07;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class GuiCliente extends JPanel {
    private JButton btMostrar;
    private JLabel lbCodigo;
    private JLabel lbNome;
    private JLabel lbEmail;
    private JTextField tfCodigo;
    private JTextField tfNome;
    private JTextField tfEmail;
    private Cliente cliente;

    public GuiCliente() {
        //construct components
        btMostrar = new JButton ("Salvar");
        lbCodigo = new JLabel ("Codigo:");
        lbNome = new JLabel ("Nome:");
        lbEmail = new JLabel ("Email:");
        tfCodigo = new JTextField (5);
        tfNome = new JTextField (5);
        tfEmail = new JTextField (5);
        cliente = new Cliente();

        //adjust size and set layout
        setPreferredSize (new Dimension (522, 298));
        setLayout (null);

        //add components
        add (btMostrar);
        add (lbCodigo);
        add (lbNome);
        add (lbEmail);
        add (tfCodigo);
        add (tfNome);
        add (tfEmail);

        //set component bounds (only needed by Absolute Positioning)
        btMostrar.setBounds (70, 240, 100, 20);
        lbCodigo.setBounds (65, 75, 100, 25);
        lbNome.setBounds (65, 120, 100, 25);
        lbEmail.setBounds (65, 170, 100, 25);
        tfCodigo.setBounds (115, 75, 100, 25);
        tfNome.setBounds (115, 120, 305, 25);
        tfEmail.setBounds (115, 170, 300, 25);
        
        btMostrar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				//JOptionPane.showMessageDialog(btMostrar, "Ola");
				
				cliente.setCodigo(Integer.parseInt(tfCodigo.getText()));
				cliente.setNome(tfNome.getText());
				cliente.setEmail(tfEmail.getText());
				JOptionPane.showMessageDialog(btMostrar, cliente.salvar());
				
				//JOptionPane.showMessageDialog(btMostrar, cliente);
			}
		});
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("GuiCliente");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GuiCliente());
        frame.pack();
        frame.setVisible (true);
    }
}
